- name: Shutdown a virtual machine {{ virtual_machine_names[item.hostname] }}
  virt:
    name: '{{ item.hostname }}.{{ openshift_install_config.cluster_domain }}'
    command: destroy
  loop: '{{ openshift_cluster_hosts }}'
  become: True
  
- name: Terminate a virtual machine {{ virtual_machine_names[item.hostname] }}
  virt:
    name: '{{ item.hostname }}.{{ openshift_install_config.cluster_domain }}'
    command: undefine
  loop: '{{ openshift_cluster_hosts }}'
  become: True

- name: Delete virtual machine volumes
  command: virsh vol-delete --pool '{{ libvirt.pool_name }}' '{{ item.hostname }}.{{ openshift_install_config.cluster_domain }}'
  loop: '{{ openshift_cluster_hosts }}'
  become: True
